name: trigger jenkins job

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  JOB_NAME: 'renting_front'
  TOKEN: '11e15bc43465e9ebbd7d5b9a32647ba98a'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger single Job
      uses: appleboy/jenkins-action@master
      with:
        url: "http://167.86.67.229:8080"
        user: "mourabit"
        token: ${{ env.TOKEN }}
        job: "${{ env.JOB_NAME }}"
