name: trigger jenkins job

# or add https://jenkins.mohamed-mourabit.com/github-webhook
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  JOB_NAME: 'renting-frontend'
  TOKEN: '11c80379c26a77d3b60f78764bb994fb4f'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger single Job
      uses: appleboy/jenkins-action@master
      with:
        url: "http://194.163.148.222:7000"
        user: "admin"
        token: ${{ env.TOKEN }}
        job: "${{ env.JOB_NAME }}"
